name: Auto Build and Install App iOS
on:
  push:
    branches: [main]
jobs:
  build-and-install-ios:
    runs-on: self-hosted
    steps:
      - name: yarn install dependencies
        run: yarn install

      - name: bundle install
        run: bundle install

      - name: pod install
        run: cd ios && pod install --repo-update && cd ..

      - name: Install App
        run: npx react-native run-ios --configuration Release --device "iPhone 12 Mini"

  test-auto-ios:
    runs-on: self-hosted
    needs: [build-and-install-ios]
    steps:
      - uses: actions/checkout@v3
      - name: Start Robot Framework for iOS App
        run: cd autotestIOS && robot test_sample_ios.robot && cd ..
