name: CI Build Android App 1
on:
  push:
    branches: [main]
jobs:
  build-android:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
          # npx react-native run-android --mode=release

      - name: Build android release
        run: |
          cd android && ./gradlew assembleRelease
