name: CI Build and Install App
on:
  push:
    branches: [main]
jobs:
  # build-and-install-android:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: yarn install dependencies
  #       run: yarn install

  #     - name: Build android release
  #       run: yarn android --mode release

  test-auto-android:
    runs-on: self-hosted
    # needs: [build-and-install-android]
    steps:
      - uses: actions/checkout@v3
      - name: Start Robot Framework for Android App
        run: robot -d reports autotestAndroid

      - name: Store test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: reports

  generate_report:
    if: always()
    needs: [test-auto-android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download test report
        uses: actions/download-artifact@v3
        with:
          name: reports
      - name: List file 1
        run: ls

      - name: Extract reports
        uses: brunoborges/justextract@v1
        with:
          file: reports
      - name: List file 2
        run: ls
      - name: Output report
        uses: joonvena/robotframework-reporter-action@v2.3
        with:
          report_path: reports
          gh_access_token: ${{ secrets.TOKEN_ACCESS }}

        # - name: Up load output report
        #   uses: joonvena/robotframework-reporter-action@v2
        #   with:
        #     report_path: autotestAndroid
        #     gh_access_token: ${{ secrets.TOKEN_ACCESS }}

  # report:
  #   if: always()
  #   needs: [test-auto-android]
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download test report
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: reports

  #     - name: Output report
  #       uses: joonvena/robotframework-reporter-action@v2.3
  #       with:
  #         report_path: autotestAndroid
  #         gh_access_token: ${{ secrets.TOKEN_ACCESS }}

  # build-and-install-ios:
  #   runs-on: self-hosted
  #   steps:
  #     - name: yarn install dependencies
  #       run: yarn install

  #     - name: bundle install
  #       run: bundle install

  #     - name: pod install
  #       run: cd ios && pod install --repo-update && cd ..

  #     - name: Install App
  #       run: npx react-native run-ios --configuration Release --device "iPhone 12 Mini"

  # test-auto-ios:
  #   runs-on: self-hosted
  #   needs: [build-and-install-ios]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Start Robot Framework for iOS App
  #       run: cd autotestIOS && robot test_sample_ios.robot && cd ..
